# Generated by Django 5.0.6 on 2024-06-23 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
