# Generated by Django 5.0.6 on 2024-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JREquipos', '0002_alter_equipo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
