# Generated by Django 5.0.6 on 2024-06-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Populares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='Populares')),
            ],
            options={
                'verbose_name': 'Populares',
                'verbose_name_plural': 'Popular',
            },
        ),
        migrations.DeleteModel(
            name='Catalogos',
        ),
    ]
