# Generated by Django 5.0.6 on 2024-06-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JRComponentes', '0002_remove_componentes_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentes',
            options={'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
    ]
