# Generated by Django 5.0.6 on 2024-06-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRComponentes', '0003_alter_componentes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentes',
            name='images',
            field=models.ImageField(upload_to='Componentes'),
        ),
    ]
