# Generated by Django 5.0.6 on 2024-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JRComponentes', '0005_alter_componentes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentes',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='componentes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
