# Generated by Django 5.0.6 on 2024-06-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JRComponentes', '0006_alter_componentes_name_alter_componentes_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentes',
            old_name='availability',
            new_name='avaiability',
        ),
    ]
