# Generated by Django 5.0.6 on 2024-06-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAudioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Audio y Video',
                'verbose_name_plural': 'Categorías de Audio y Video',
            },
        ),
        migrations.CreateModel(
            name='ComponenteAudioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='AudioVideo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('availability', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JRAudio_video.categoriaaudiovideo')),
            ],
            options={
                'verbose_name': 'Componente de Audio y Video',
                'verbose_name_plural': 'Componentes de Audio y Video',
            },
        ),
    ]
